### ISSUE TITLE
Load vcf file from predefined URL

### ISSUE THREAD

**Issue by danielecook** [jsa-aerial/js-local-vcf#1]
Hi - I am trying to load a VCF File from a predefined URL within the browser. Is there a way to go about doing that with this?

Thank you!

**Comment by jsa-aerial** [comment]
Hi Daniel,

If you are wondering if this works for urls as well as local files, the
answer is it only works for local files. So, if you are trying to parse a
remote vcf identified by a url without downloading it first, you need
something else.

/Jon

**Comment by danielecook** [comment]
Thanks that answers my question!

Dan
