### ISSUE TITLE
initialize bgzf

### ISSUE THREAD

**Issue by danielecook** [jsa-aerial/js-local-vcf#2]
Hi I have one other question - I'm still trying to play around and figure things out. How do you initialize the BGZF file spec?

"// readBinaryVCF which takes a tabix filespec and a BGZF VCF filespec
// initializes a tabix reader and builds binary VCF reader.  Provides
// methods"

Would I be able to do something like this?

```
var tbx = new readTabixFile("http://local_file/20150510_V4_WI.vcf.gz.csi")
var vcf_file = new bgzf("http://local_file/20150510_V4_WI.vcf.gz");

var vcf = new readBinaryVCF(tbx, vcf)
```

I think if I can get access to the functions and the vcf is loaded I should be good to go. Thanks!

**Comment by jsa-aerial** [comment]
Hi Daniel,

The basic story on this is that it is intended only for local files via the
JS File API (specifically, the FileReader).  Due all the security
restrictions there you cannot programmatically access the user's file
system.  So, you have to use a file dialog via an input element.  Something
like

<input type="file" id="binaryfileinput" multiple />
Then the user needs to use the dialog to navigate to and then select the
files (in this case the tabix and bgzf vcf).  Then you can register an
event for this action on a JS function which will then scoop up the files
from the input element and be able to then call the main constructor.  So,
something like this:

<script type="text/javascript">
  document.getElementById('binaryfileinput').addEventListener(
      'change', initVCFR, false);
</script>

var vcfR;
function initVCFR(evt) {
    files = evt.target.files;
    var tbi, vcf;
    if (files[0].name.split(".").slice(-1)[0] == "tbi") {
      tbi = files[0];
      vcf = files[1];
    } else {
      tbi = files[1];
      vcf = files[2];
    };
    vcfR = new readBinaryVCF(tbi,vcf,readyfn);
}

/Jon

**Comment by danielecook** [comment]
Thanks Jon - I am not terribly familiar with javascript. 

I really appreciate the help on this. Do you know if it is technically possible to read a vcf file from a URL (on the same domain) using javascript or would I need to rely on a server-side solution for that? 

I figured that given the speed with which tabix indices can be used to query variants, it could be used in place of a database to access variant information.

**Comment by jsa-aerial** [comment]
Hi Daniel,

On Fri, May 15, 2015 at 12:16 PM, Daniel E Cook notifications@github.com
wrote:

> I really appreciate the help on this. Do you know if it is technically
> possible to read a vcf file from a URL (on the same domain) using
> javascript or would I need to rely on a server-side solution for that?
> 
> There really is no 'good' way to do this.  You _can_ programmatically
> download a file (using various gyrations), but it will go to your download
> folder, so you will still need to use a file dialog approach to get at it.
> The other option, as you note, is to use a server side solution. There are
> two 'primary' options for that:
- Read and parse the files on the server and just send desired results to
  the client.
- Use the server to read the files and stream them back to the client.

Both approaches will best be done by using websockets, though the first
could probably be done reasonably well with http/ajax (though that would
not be as nice - flexible and natural).

Also it is worth noting that JS is easily 1/15 as fast at parsing tabix (or
bam bais) as JVM languages (Java, Clojure, et. al.) or C solutions; i.e.,
JVM and C are 15 times faster. So, if you are mostly (or only) dealing with
remote files (via urls) a server approach is the way to go.  If you are
dealing with smaller files, this won't really be a factor, but if you are
dealing with large tbis (10+ MB), this performance issue will be noticeable.

If you go the server route, but still have local files that you need to
deal with, you could open the tbi and vcf files (via file dialog) and then
use this js-local-vcf lib to work them directly and use the server for the
remote stuff.

Hope that helps!

/Jon

**Comment by danielecook** [comment]
Thanks Jon. I'll probably go with using the server to read and stream back to the client with bcftools. 

Tremendous help!
