### ISSUE TITLE
Retrieving Multiple Discontinuous Records

### ISSUE THREAD

**Issue by charliecurnin** [jsa-aerial/js-local-vcf#3]
Hi, 

Again, thanks for building such a great library, and for being so willing to provide support for it. I also sent you guys an email about this issue; I'm realizing now that I should have posted it here. 

Basically, what I'd like to do is use the getRecords() method multiple times—with the same files—but in different chromosomes, from different start points to different points, in sections which are not contiguous. 

I have a working solution, but it's slow and seems overcomplicated. I'm not an experienced JavaScript developer, and with other, simpler approaches I tried (like using the same object for multiple getRecords() calls—dumb, I know; or recursion, for example), I ran into problems with asynchronicity and certain properties (like indexReader.bhash) seemingly uninitialized when I wanted to use them. 

``` javascript
var d = []; 
var readers = []; 
var callbacksRemaining = regions.length; 

regions.forEach(function(item, i) {

    readers[i] = new readBinaryVCF(tabix, vcf, function(tabixReader) {

        reader = readers[i];

        var index = 0; 

        for (key in tabixReader.idxContent.namehash) {
            if (key == regions[i][0]) {
                index = tabixReader.idxContent.namehash[key];
            }
        }

        reader.getRecords(index, regions[i][1], regions[i][2], function(data) {; 

            d[i] = data; 
            callbacksRemaining--; 

            if (callbacksRemaining <= 0) {
                processData(d);
            }
        });
    });
});
```

If there's a better way to do this (which I assume there is), please let me know.

**Comment by jsa-aerial** [comment]
Hi
It looks like the version that was in the repo did not have the more appropriate callback behavior for the readBinaryVCF. It just passed the cb to the tabix getIndex which typically wouldn't help. Now the callback to readBinaryVCF  will be notified when the reading of the tabix is done and the initialization of the cache values parsed from it is fully done and the VCF reader is fully initialized. It is called with the initialized VCF reader.  So, something like this should work for you:

``` javascript

var regions = [ 
        [10, 10000, 100000], 
        [12, 10000, 100000], 
        [14, 10000, 100000], 
        [18, 10000, 100000]
    ];
var d = [];
function doRecords (vcfR) {
  for (var i = 0; i < regions.length; i++) {
    reg = regions[i]
    vcfR.getRecords(reg[0], reg[1], reg[2], function(data) {d[i] = data});
  }

vcfR = new readBinaryVCF(tabix, vcf, doRecords)
```

**Comment by charliecurnin** [comment]
Using that model, I now get `TypeError: vcfR.getRecords is not a function. (in 'vcfR.getRecords', 'vcfR.getRecords' is undefined)`.

var reader = new readBinaryVCF(tabix, vcf, function(vcfR) {

		regions.forEach(function(item, i) {

			var index = 0; 

			for (key in vcfR.idxContent.namehash) {
				if (key == item[0]) {
					index = vcfR.idxContent.namehash[key];
				}
			}

			vcfR.getRecords(index, parseInt(item[1]), parseInt(item[1]), function(data) {

				combinedData[i] = data; 
				callbacksRemaining--;  

				if (callbacksRemaining <= 0) {
					processData(combinedData);
				}
			});
		});
	});

**Comment by charliecurnin** [comment]
Thanks! This works great—except I think you meant `reader.getRecords(...)` and not `vcfR.getRecords(...)`. The latter crashes; the former works perfectly.

**Comment by jsa-aerial** [comment]
You will see that in the example I gave, there is no 'reader' - I used vcfR for that and so, in that example, vcfR.getRecords is correct. In your original code you use 'readers', and so, if you changed that to 'reader', then there would be no vcfR in your code and using 'vcfR' would obviously crash, while using 'reader' would work.

**Comment by jsa-aerial** [comment]
Also, just to be clear, doRecords (in my example) uses the 'vcfR' which is its _argument_. That's important as the outer one would not be available at the time doRecords is called!

**Comment by jsa-aerial** [comment]
Hmmmm, upon closer examination, there was still something wrong with the call context. I would have thought that the 'this' for vcfReader would have been closed over in the wrapped callback, but it looks to be using the tabix 'this' in the call. Just changed that to be explicit.

**Comment by charliecurnin** [comment]
Cool. Thanks!

**Comment by jsa-aerial** [comment]
You're welcome!
