### ISSUE TITLE
Detect Mismatched Tabix and VCF

### ISSUE THREAD

**Issue by charliecurnin** [jsa-aerial/js-local-vcf#5]
Hi, 

I'm using `readBinaryVCF()` and `getRecords()` to access data from a VCF. 

I know this is a fringe case, but I'm wondering if there's some way to detect if someone is using a VCF and a Tabix that don't match—meaning the Tabix is the index file for another VCF. Right now, it just outputs a bunch of errors to the console; instead, I'd like to change something on my graphical interface. 

I've had little success with `try...catch`, too, unfortunately. 

Thank you for your help. 

```
var reader = new readBinaryVCF(tabix, vcf, function(vcfR) {
    reader.getRecords(index, parseInt(item[1]), parseInt(item[1]), function(data) {
        processData(data);
    });
});
```

**Comment by jsa-aerial** [comment]
The problem here is that the tabix file does not include any information about the vcf file it was generated from. So, there isn't any way to really verify the two match.

**Comment by charliecurnin** [comment]
Thanks for the quick response. 

Is there any way to catch the errors that result when they don't match?

**Comment by jsa-aerial** [comment]
If they are exceptions, you can use try/catch - a blunt approach but possibly useful depending on circumstance. If the 'errors' are bad/incorrect results, sadly, that is rather more difficult to get a hold on.

**Comment by charliecurnin** [comment]
Got it.

Wrapping any of the lines of code I write in try/catch doesn't seem to do anything—should I go into the libraries or files you've provided to add try/catch?

Thanks again.

**Comment by jsa-aerial** [comment]
That sounds like the errors are not exceptions (if they were, you would be able to catch them in your try/catch blocks), so trying to catch 'them' at lower levels wouldn't work either. What exactly are you seeing?

Also, it is totally plausible that the better way to try to catch this is at user input time - force the files to have matching names which should at least greatly reduce this issue.

**Comment by charliecurnin** [comment]
Totally right about trying to catch it as the files are uploaded. I know it would probably never happen that a user uploaded a VCF and TBI that had the same name but didn't actually match each other, but I'm just trying to be exhaustive. 

What I'm seeing right now is a group of errors coming from inflate.js: `invalid literal/length code`,`invalid stored block lengths`, `invalid block type`, `invalid stored block lengths`, `invalid block type`, `too many length or distance symbols`.

![screen shot 2016-08-11 at 10 06 08 am](https://cloud.githubusercontent.com/assets/11037337/17591284/84a66b76-5fab-11e6-91a6-ca0ae10f3e05.png)

**Comment by jsa-aerial** [comment]
Those are exceptions being thrown by jszlib_inflate_buffer and nothing is explicitly catching them so the top level JS interpreter catches and displays the stack trace. So, you should be able to catch these if you put the catch in the 'right' place, but again, I don't see that being particularly useful (and could even be misleading).

**Comment by charliecurnin** [comment]
Hmm. Understood. 

Thanks!
